import os
from navlib import nav
import sys, asyncio; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from playwright.async_api import async_playwright
from ai_lib import sql
BASE = os.environ.get('LUMINA_URL', 'http://127.0.0.1:8080').rstrip('/'); ok=lambda c: 'PASSOU' if c else '*** FALHOU ***'
async def login(pg,email,pw='123456'):
    await pg.goto(BASE+'/index.php'); await pg.fill('#login-form [name=email]',email); await pg.fill('#login-form [name=password]',pw)
    await pg.click('#login-form button[type=submit]'); await pg.wait_for_url('**/dashboard.php'); await pg.wait_for_timeout(1500)
    await pg.add_style_tag(content='html{scroll-behavior:auto!important} #weather-chip{visibility:hidden!important}')
async def main():
    sql("DELETE FROM notes"); sql("DELETE FROM login_attempts"); sql("DELETE FROM calendar_events WHERE event_date=CURDATE()")
    async with async_playwright() as p:
        b=await p.chromium.launch(); ctx=await b.new_context(locale='pt-PT', viewport={'width':1366,'height':900}); await ctx.add_init_script("localStorage.setItem('gf-reptil','off')")
        pg=await ctx.new_page(); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('console',lambda m:errs.append(m.text) if m.type=='error' and 'open-meteo' not in m.text and 'ERR_FAILED' not in m.text else None)
        await login(pg,'maria@teste.pt'); await nav(pg,'notes'); await pg.wait_for_timeout(900)
        print('=== ESTADO VAZIO ===')
        print('lista:', (await pg.inner_text('#note-list')).replace('\n',' | ')[:90], ok('Ainda não tens notas' in await pg.inner_text('#note-list')), '| editor:', ok('Escolhe uma nota' in await pg.inner_text('#note-empty')))
        print('\n=== CRIAR E GUARDAR AUTOMATICAMENTE ===')
        await pg.click('#note-new'); await pg.fill('#note-form [name=title]','Ideias de campanha'); await pg.fill('#note-form [name=detail]','Black Friday com frete grátis.\nPostar às 18h.')
        print('a escrever…:', await pg.inner_text('#note-status'), ok('escrever' in await pg.inner_text('#note-status') or 'guardar' in await pg.inner_text('#note-status')))
        await pg.wait_for_timeout(1900); st=await pg.inner_text('#note-status'); print('depois de parar de escrever:', st, ok('Guardado às' in st)); print('   na base de dados:', sql("SELECT CONCAT(title,' | ',shared,' | ',color) FROM notes"), ok(sql("SELECT COUNT(*) FROM notes")=='1'))
        await pg.fill('#note-tag-input','marketing'); await pg.press('#note-tag-input','Enter'); await pg.fill('#note-tag-input','ideias,'); await pg.press('#note-tag-input','Enter'); await pg.click('.note-swatch.note-coral'); await pg.click('#note-pin'); await pg.wait_for_timeout(1800)
        print('etiquetas/cor/fixar:', sql("SELECT CONCAT(tags,' | ',color,' | fixada=',pinned) FROM notes"), ok('"marketing"' in sql("SELECT tags FROM notes") and sql("SELECT color FROM notes")=='coral' and sql("SELECT pinned FROM notes")=='1'))
        print('   a nota ainda é única (editou, não duplicou):', ok(sql("SELECT COUNT(*) FROM notes")=='1'), '| cor do editor:', await pg.get_attribute('.note-editor','data-color'))
        await pg.click('#note-new'); await pg.fill('#note-form [name=title]','Lista de compras'); await pg.fill('#note-form [name=detail]','Etiquetas, caixas, fita'); await pg.wait_for_timeout(1800)
        cards=await pg.evaluate("[...document.querySelectorAll('.note-card')].map(c=>c.querySelector('b').textContent+(c.querySelector('.note-pin')?' 📌':''))"); print('lista:', cards, ok(cards[0].endswith('📌') and len(cards)==2), '(fixada em primeiro)')
        await pg.screenshot(path=''+os.environ.get('LUMINA_SHOTS','/tmp')+'/notes.png', full_page=True)
        print('\n=== PESQUISA E FILTRO ===')
        await pg.fill('#note-search','frete'); await pg.wait_for_timeout(800); print('pesquisar "frete":', await pg.evaluate("[...document.querySelectorAll('.note-card b')].map(b=>b.textContent)"), ok(await pg.locator('.note-card').count()==1))
        await pg.fill('#note-search','zzz'); await pg.wait_for_timeout(800); print('sem resultados:', ok('Nenhuma nota encontrada' in await pg.inner_text('#note-list')))
        await pg.fill('#note-search',''); await pg.wait_for_timeout(800); await pg.click('.note-tag-filter[data-tag=marketing]'); await pg.wait_for_timeout(700); print('filtrar #marketing:', await pg.locator('.note-card').count(), 'nota', ok(await pg.locator('.note-card').count()==1)); await pg.click('.note-tag-filter[data-tag=""]'); await pg.wait_for_timeout(600)
        print('\n=== ABRIR E EDITAR UMA EXISTENTE ===')
        await pg.click('.note-card:has-text("Lista de compras")'); print('abre no editor:', await pg.input_value('#note-form [name=title]'), ok(await pg.input_value('#note-form [name=title]')=='Lista de compras'), '| botão Apagar visível:', ok(await pg.is_visible('#note-delete')))
        await pg.fill('#note-form [name=detail]','Etiquetas, caixas, fita, saquetas'); await pg.wait_for_timeout(1800); print('   editada na BD:', sql("SELECT detail FROM notes WHERE title='Lista de compras'"), ok('saquetas' in sql("SELECT detail FROM notes WHERE title='Lista de compras'") and sql("SELECT COUNT(*) FROM notes")=='2'))
        print('\n=== FALHA DE REDE: não perde o texto ===')
        await pg.route('**/api/notes.php', lambda r: r.abort()); await pg.fill('#note-form [name=detail]','texto escrito sem ligação'); await pg.wait_for_timeout(1800)
        print('estado:', await pg.inner_text('#note-status'), ok('rascunho' in await pg.inner_text('#note-status'))); print('   rascunho guardado no dispositivo:', ok('sem ligação' in (await pg.evaluate("localStorage.getItem('gf-note-draft')") or '')))
        await pg.unroute('**/api/notes.php'); await pg.fill('#note-form [name=detail]','texto escrito sem ligação (agora com ligação)'); await pg.wait_for_timeout(1800); print('   com a ligação de volta guarda:', await pg.inner_text('#note-status'), ok('Guardado' in await pg.inner_text('#note-status')), '| rascunho limpo:', ok(not await pg.evaluate("localStorage.getItem('gf-note-draft')")))
        print('\n=== TEXTO MALICIOSO ===')
        await pg.click('#note-new'); await pg.fill('#note-form [name=title]','<img src=x onerror=window.__n=1>'); await pg.fill('#note-form [name=detail]','<script>window.__m=1</script>'); await pg.wait_for_timeout(1800); await pg.reload(); await pg.wait_for_timeout(1500); await nav(pg,'notes'); await pg.wait_for_timeout(900)
        x=await pg.evaluate("({n:window.__n,m:window.__m,imgs:document.querySelectorAll('.note-card img').length,txt:document.querySelector('.note-list').innerText.includes('<img')})"); print('nada executou:', ok(x['n'] is None and x['m'] is None and x['imgs']==0), '| aparece como texto:', ok(x['txt']))
        print('\n=== APAGAR ===')
        await pg.click('.note-card:has-text("Lista de compras")'); await pg.click('#note-delete'); await pg.wait_for_selector('.ux-confirm'); print('pede confirmação:', (await pg.inner_text('.ux-confirm h2')).strip()); await pg.click('.ux-confirm [data-no]'); await pg.wait_for_timeout(400); print('   cancelar mantém:', ok(sql("SELECT COUNT(*) FROM notes WHERE title='Lista de compras'")=='1'))
        await pg.click('#note-delete'); await pg.wait_for_selector('.ux-confirm'); await pg.click('.ux-confirm [data-yes]'); await pg.wait_for_timeout(900); print('   confirmar apaga:', ok(sql("SELECT COUNT(*) FROM notes WHERE title='Lista de compras'")=='0'), '| editor volta ao estado vazio:', ok(await pg.is_visible('#note-empty')))
        print('\nERROS JS:', [e for e in errs if 'net::ERR' not in e] or 'nenhum'); await b.close()
        # funcionário
        b=await p.chromium.launch(); ctx=await b.new_context(locale='pt-PT', viewport={'width':1366,'height':900}); await ctx.add_init_script("localStorage.setItem('gf-reptil','off')"); pg=await ctx.new_page(); await login(pg,'cal@teste.pt'); await nav(pg,'notes'); await pg.wait_for_timeout(900)
        print('\n=== FUNCIONÁRIO ===\naba Notas disponível (mesmo sem permissões de área):', ok(True), '| vê as notas privadas do dono?', ok('Ideias de campanha' not in await pg.inner_text('#note-list')))
        await pg.click('#note-new'); await pg.fill('#note-form [name=title]','Aviso da equipa'); await pg.fill('#note-form [name=detail]','Reunião às 10h'); await pg.check('#note-form [name=shared]'); await pg.wait_for_timeout(1800)
        print('nota partilhada guardada:', sql("SELECT shared FROM notes WHERE title='Aviso da equipa'"), ok(sql("SELECT shared FROM notes WHERE title='Aviso da equipa'")=='1'))
        await b.close()
        b=await p.chromium.launch(); ctx=await b.new_context(locale='pt-PT', viewport={'width':1366,'height':900}); await ctx.add_init_script("localStorage.setItem('gf-reptil','off')"); pg=await ctx.new_page(); await login(pg,'maria@teste.pt'); await nav(pg,'notes'); await pg.wait_for_timeout(900)
        print('o dono vê a partilhada com o nome do autor:', await pg.evaluate("[...document.querySelectorAll('.note-card')].filter(c=>c.textContent.includes('Aviso da equipa')).map(c=>c.querySelector('.note-meta small').textContent)"), ok(await pg.locator('.note-card:has-text("Aviso da equipa")').count()==1))
        await b.close()
if __name__=="__main__": asyncio.run(main())
