"""Estoque com variações + vendas ligadas ao estoque + produtos mais vendidos + palavra-passe/nome (v16).
Parte 1 (API, como o navegador a usa): criar produtos (sem/com tamanhos e cores), validações, duplicados, editar, vender, vender a mais,
  estoque a descer, total automático/manual, data automática, esgotado, ranking, editar/anular/apagar venda, repetição do mesmo pedido,
  vendas ao mesmo tempo (nunca fica negativo).
Parte 2 (ecrã): formulário de produto, filtros, venda em cascata (só tamanhos/cores com estoque), atualização imediata, ecrãs pequenos,
  botão da palavra-passe fora da página inicial e dentro da Área pessoal, nome junto à foto, sem erros na consola."""
import asyncio, os, subprocess, sys, json, uuid
from playwright.async_api import async_playwright
sys.path.insert(0, os.path.dirname(__file__))
from navlib import nav
BASE = os.environ.get('LUMINA_URL', 'http://127.0.0.1:8086').rstrip('/')
bad = 0
def ok(c):
    global bad
    if not c: bad += 1
    return 'PASSOU' if c else '*** FALHOU ***'
def sql(q): return subprocess.run(['mysql', '--default-character-set=utf8mb4', '-uroot', 'gestao_facil', '-N', '-e', q], capture_output=True, text=True).stdout.strip()
UID = sql("SELECT id FROM users WHERE email='maria@teste.pt'")
TAG = ' QA16'

async def call(pg, url, body=None, method='POST'):
    return await pg.evaluate("""async ([u, b, m]) => { const r = await fetch('api/' + u, { method: m, credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: b ? JSON.stringify({ ...b, csrf: window.GF_CSRF || csrf }) : undefined }); let d = {}; try { d = await r.json(); } catch (e) {} return { s: r.status, d }; }""", [url, body, method])

async def main():
    sql(f"DELETE FROM sale_orders WHERE user_id={UID}; DELETE FROM sales WHERE user_id={UID} AND (product_name LIKE '%{TAG}' OR is_demo=1); DELETE FROM products WHERE user_id={UID} AND name LIKE '%{TAG}'")
    sql(f"INSERT INTO business_profiles (user_id,business_name,business_type,onboarding_done_at) VALUES ({UID},'Loja QA','clothing',NOW()) ON DUPLICATE KEY UPDATE business_type='clothing',onboarding_done_at=NOW(); DELETE FROM login_attempts; UPDATE users SET preferences=NULL WHERE id={UID}")
    async with async_playwright() as p:
        b = await p.chromium.launch()
        ctx = await b.new_context(locale='pt-PT', viewport={'width': 1366, 'height': 900})
        await ctx.add_init_script("localStorage.setItem('lumina-aviso-cookies','1');sessionStorage.setItem('lumina-oi','1');localStorage.setItem('gf-reptil','off')")
        pg = await ctx.new_page(); errs = []
        pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' and 'ERR_' not in m.text and 'open-meteo' not in m.text and '409' not in m.text and '400' not in m.text and '404' not in m.text and '422' not in m.text and '404' not in m.text else None)
        pg.on('pageerror', lambda e: errs.append(str(e)))
        await pg.goto(BASE + '/index.php'); await pg.fill('#login-form [name=email]', 'maria@teste.pt'); await pg.fill('#login-form [name=password]', '123456')
        await pg.click('#login-form button[type=submit]'); await pg.wait_for_url('**/dashboard.php'); await pg.wait_for_timeout(1500)

        print('=== 1) PRODUTOS E VARIAÇÕES (API) ===')
        r = await call(pg, 'data.php?module=products', {'name': 'Meia simples' + TAG, 'sale_price': 5, 'cost_price': 2, 'minimum_stock': 2, 'variants': [{'quantity': 10}]})
        print('produto sem tamanho nem cor:', ok(r['s'] == 201), sql(f"SELECT COUNT(*),SUM(quantity) FROM product_variants WHERE product_id={r['d'].get('id', 0)}"))
        plain = r['d']['id']
        V = [{'size': 'S', 'color': 'Preto', 'quantity': 5}, {'size': 'M', 'color': 'Preto', 'quantity': 8}, {'size': 'L', 'color': 'Branco', 'quantity': 3}, {'size': 'XL', 'color': 'Azul', 'quantity': 2}]
        r = await call(pg, 'data.php?module=products', {'name': 'Camisa Nike' + TAG, 'brand': 'Nike', 'category': 'Camisas', 'sku': 'NK-001', 'sale_price': 25, 'cost_price': 10, 'minimum_stock': 3, 'variants': V})
        nike = r['d']['id']
        print('produto com vários tamanhos e cores (4 combinações):', ok(r['s'] == 201 and sql(f"SELECT COUNT(*) FROM product_variants WHERE product_id={nike}") == '4'))
        print('estoque do produto = soma das variações (18):', ok(sql(f"SELECT stock_quantity FROM products WHERE id={nike}") == '18'))
        r2 = await call(pg, 'data.php?module=products', {'name': 'Camisa Nike' + TAG, 'brand': 'Nike', 'sale_price': 25, 'variants': [{'quantity': 1}]})
        print('produto repetido (mesmo nome e marca) é recusado e indica qual editar:', ok(r2['s'] == 409 and r2['d'].get('duplicate_id') == nike), r2['d'].get('error', '')[:60])
        r2 = await call(pg, 'data.php?module=products', {'name': 'Camisa Nike' + TAG, 'brand': 'Adidas', 'sale_price': 25, 'variants': [{'size': 'M', 'quantity': 1}]})
        print('mesmo nome com OUTRA marca é permitido:', ok(r2['s'] == 201)); other = r2['d'].get('id')
        r2 = await call(pg, 'data.php?module=products', {'name': 'Dup combo' + TAG, 'sale_price': 5, 'variants': [{'size': 'M', 'color': 'preto', 'quantity': 1}, {'size': 'm', 'color': 'Preto', 'quantity': 2}]})
        print('duas variações com o mesmo tamanho e cor (sem distinguir maiúsculas): recusado:', ok(r2['s'] == 400), r2['d'].get('error', '')[:50])
        r2 = await call(pg, 'data.php?module=products', {'name': 'Neg' + TAG, 'sale_price': 5, 'variants': [{'quantity': -1}]})
        print('quantidade negativa recusada:', ok(r2['s'] == 400), r2['d'].get('error', ''))
        r2 = await call(pg, 'data.php?module=products', {'name': 'Dec' + TAG, 'sale_price': 5, 'variants': [{'quantity': '2,5'}]})
        print('quantidade decimal recusada:', ok(r2['s'] == 400))
        r2 = await call(pg, 'data.php?module=products', {'name': 'Preço' + TAG, 'sale_price': 'abc', 'variants': [{'quantity': 1}]})
        print('preço inválido recusado:', ok(r2['s'] == 400), r2['d'].get('error', ''))
        r2 = await call(pg, 'data.php?module=products', {'name': '', 'sale_price': 5, 'variants': [{'quantity': 1}]})
        print('nome vazio recusado:', ok(r2['s'] == 400))
        print('nada foi criado pelos pedidos recusados:', ok(sql(f"SELECT COUNT(*) FROM products WHERE user_id={UID} AND name IN ('Dup combo{TAG}','Neg{TAG}','Dec{TAG}','Preço{TAG}')") == '0'))

        print('=== 2) EDITAR UM PRODUTO ===')
        vids = {f"{v[0]}|{v[1]}": v[2] for v in [x.split('\t') for x in sql(f"SELECT COALESCE(size,''),COALESCE(color,''),id FROM product_variants WHERE product_id={nike}").split('\n')]}
        r = await call(pg, 'data.php?module=product_update', {'id': nike, 'name': 'Camisa Nike' + TAG, 'brand': 'Nike', 'category': 'Camisas', 'sale_price': 29.9, 'cost_price': 10, 'minimum_stock': 3,
              'variants': [{'id': int(vids['M|Preto']), 'size': 'M', 'color': 'Preto', 'quantity': 9, 'price': ''}, {'size': 'M', 'color': 'Branco', 'quantity': 4}]})
        print('editar: mudar preço, quantidade de uma variação e acrescentar nova cor:', ok(r['s'] == 200), r['d'])
        print('  preço novo 29.90 / total = 5+9+3+2+4 = 23:', ok(sql(f"SELECT sale_price,stock_quantity FROM products WHERE id={nike}") == '29.90\t23'))
        r = await call(pg, 'data.php?module=product_update', {'id': nike, 'name': 'Camisa Nike' + TAG, 'brand': 'Nike', 'sale_price': 29.9, 'variants': [{'size': 'S', 'color': 'Branco', 'quantity': 1}, {'size': 'S', 'color': 'preto', 'quantity': 1}]})
        print('editar: combinação que já existe (S Preto) é recusada:', ok(r['s'] in (409, 400)), r['d'].get('error', ''))
        r = await call(pg, 'data.php?module=product_update', {'id': nike, 'name': 'Camisa Nike' + TAG, 'brand': 'Nike', 'sale_price': 29.9, 'variants': [{'id': int(vids['M|Preto']), 'size': 'M', 'color': 'Preto', 'quantity': 9}], 'expected': {vids['M|Preto']: 1}})
        print('editar: estoque mudou entretanto -> conflito, nada gravado:', ok(r['s'] == 409 and r['d'].get('conflict')))
        r = await call(pg, 'data.php?module=product_update', {'id': nike, 'name': 'Camisa Nike' + TAG, 'brand': 'Nike', 'sale_price': 29.9, 'image_url': 'javascript:alert(1)', 'variants': []})
        print('editar: imagem que não é http(s) recusada:', ok(r['s'] == 400))

        print('=== 3) VENDER ===')
        VM = int(vids['M|Preto'])
        key = str(uuid.uuid4())
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 2, 'request_key': key})
        sale1 = r['d'].get('id')
        print('venda válida (2 un. de M Preto):', ok(r['s'] == 201), r['d'].get('remaining'))
        print('  estoque da variação desceu de 9 para 7:', ok(sql(f"SELECT quantity FROM product_variants WHERE id={VM}") == '7'))
        print('  estoque do produto desceu para 21:', ok(sql(f"SELECT stock_quantity FROM products WHERE id={nike}") == '21'))
        print('  valor total automático = 2 × 29,90 = 59,80:', ok(sql(f"SELECT amount FROM sales WHERE id={sale1}") == '59.80'))
        print('  data e hora preenchidas pelo servidor (agora):', ok(abs(int(sql(f"SELECT TIMESTAMPDIFF(SECOND,sold_at,NOW()) FROM sales WHERE id={sale1}"))) < 120))
        print('  retrato guardado (nome, marca, tamanho, cor, preço unitário):', sql(f"SELECT product_name,brand,size,color,unit_price,status FROM sales WHERE id={sale1}"))
        print('  existe cabeçalho da venda e movimento de estoque -2:', ok(sql(f"SELECT COUNT(*) FROM sale_orders WHERE id=(SELECT sale_order_id FROM sales WHERE id={sale1})") == '1' and sql(f"SELECT quantity FROM stock_movements WHERE sale_id={sale1} AND type='sale'") == '-2'))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 2, 'request_key': key})
        print('o MESMO pedido repetido (recarregar/duplo clique) não vende outra vez:', ok(r['s'] == 200 and r['d'].get('duplicate') and sql(f"SELECT quantity FROM product_variants WHERE id={VM}") == '7' and sql(f"SELECT COUNT(*) FROM sales WHERE user_id={UID} AND product_name='Camisa Nike{TAG}'") == '1'))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 99, 'request_key': str(uuid.uuid4())})
        print('vender mais do que existe:', ok(r['s'] == 409 and r['d'].get('error') == 'A quantidade selecionada é superior ao stock disponível.' and r['d'].get('available') == 7), r['d'].get('error'))
        print('  estoque não mudou (7):', ok(sql(f"SELECT quantity FROM product_variants WHERE id={VM}") == '7'))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 0, 'request_key': str(uuid.uuid4())})
        print('quantidade 0 recusada:', ok(r['s'] == 400), r['d'].get('error'))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'quantity': 1, 'product_name': 'Produto inventado', 'request_key': str(uuid.uuid4())})
        print('texto livre / produto que não existe: recusado:', ok(r['s'] in (404, 400)), r['d'].get('error'))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': 99999999, 'quantity': 1, 'request_key': str(uuid.uuid4())})
        print('variação inexistente: recusada:', ok(r['s'] == 404))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 1, 'amount': 50, 'request_key': str(uuid.uuid4())})
        sale2 = r['d'].get('id')
        print('valor total alterado à mão fica guardado (50,00) e o preço de catálogo no item:', ok(sql(f"SELECT amount,unit_price FROM sales WHERE id={sale2}") == '50.00\t29.90'))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 1, 'amount': -5, 'request_key': str(uuid.uuid4())})
        print('valor total negativo recusado:', ok(r['s'] == 400))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 1, 'sold_at': '2001-01-01T10:00', 'request_key': str(uuid.uuid4())})
        print('a data enviada pelo navegador é ignorada para o dono? (dono pode, funcionário não):', r['s'], sql(f"SELECT sold_at FROM sales WHERE id={r['d'].get('id', 0)}"))
        # produto sem tamanho/cor: pode vender só com product_id
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'product_id': plain, 'quantity': 3, 'request_key': str(uuid.uuid4())})
        print('produto sem tamanho/cor vende-se só com o produto (10 → 7):', ok(r['s'] == 201 and sql(f"SELECT stock_quantity FROM products WHERE id={plain}") == '7'))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'product_id': nike, 'quantity': 1, 'request_key': str(uuid.uuid4())})
        print('produto com várias variações exige escolher o tamanho/cor:', ok(r['s'] == 400), r['d'].get('error'))

        print('=== 4) ESGOTADO E INATIVO ===')
        VX = int(vids['XL|Azul'])
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VX, 'quantity': 2, 'request_key': str(uuid.uuid4())})
        print('vender as últimas 2 unidades de XL Azul:', ok(r['s'] == 201 and r['d'].get('remaining') == 0))
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VX, 'quantity': 1, 'request_key': str(uuid.uuid4())})
        print('variação esgotada não se pode vender:', ok(r['s'] == 409), r['d'].get('error'))
        sell = await pg.evaluate("async () => { const d = await api('data.php?module=products'); const s = GFVar.sellable(d.items).find(p => p.name.includes('Camisa Nike QA16') && p.brand === 'Nike'); return s ? s.variants.map(v => (v.size||'') + '|' + (v.color||'')).sort() : null; }")
        print('lista de venda só tem combinações com estoque (sem XL|Azul):', ok(sell and 'XL|Azul' not in sell and 'M|Preto' in sell), sell)
        await call(pg, 'data.php?module=product_update', {'id': plain, 'name': 'Meia simples' + TAG, 'sale_price': 5, 'status': 'inactive', 'variants': []})
        r = await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'product_id': plain, 'quantity': 1, 'request_key': str(uuid.uuid4())})
        print('produto inativo não se vende:', ok(r['s'] == 409), r['d'].get('error'))
        await call(pg, 'data.php?module=product_update', {'id': plain, 'name': 'Meia simples' + TAG, 'sale_price': 5, 'status': 'active', 'variants': []})

        print('=== 5) EDITAR / ANULAR / APAGAR VENDA ===')
        before = int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}"))
        r = await call(pg, 'insights.php', {'action': 'sale_update', 'kind': 'sales', 'id': sale1, 'quantity': 4})
        print('editar venda 2 → 4 un.: estoque desce 2 e o total recalcula (119,60):', ok(r['s'] == 200 and int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == before - 2 and sql(f"SELECT amount FROM sales WHERE id={sale1}") == '119.60'))
        r = await call(pg, 'insights.php', {'action': 'sale_update', 'kind': 'sales', 'id': sale1, 'quantity': 1})
        print('editar venda 4 → 1 un.: estoque repõe 3:', ok(r['s'] == 200 and int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == before + 1))
        r = await call(pg, 'insights.php', {'action': 'sale_update', 'kind': 'sales', 'id': sale1, 'quantity': 500})
        print('editar para mais do que existe: recusado, estoque igual:', ok(r['s'] == 409 and int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == before + 1), r['d'].get('error'))
        r = await call(pg, 'insights.php', {'action': 'sale_update', 'kind': 'sales', 'id': sale1, 'amount': 33.3})
        print('editar só o valor total (33,30): quantidade e estoque não mudam:', ok(r['s'] == 200 and sql(f"SELECT quantity,amount FROM sales WHERE id={sale1}") == '1\t33.30'))
        q0 = int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}"))
        r = await call(pg, 'insights.php', {'action': 'sale_cancel', 'kind': 'sales', 'id': sale1})
        print('anular venda: estoque repõe 1:', ok(r['s'] == 200 and int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == q0 + 1 and sql(f"SELECT status FROM sales WHERE id={sale1}") == 'cancelled'))
        r = await call(pg, 'insights.php', {'action': 'sale_cancel', 'kind': 'sales', 'id': sale1})
        print('anular outra vez NÃO repõe duas vezes:', ok(r['s'] == 200 and int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == q0 + 1))
        r = await call(pg, 'insights.php', {'action': 'sale_update', 'kind': 'sales', 'id': sale1, 'quantity': 2})
        print('venda anulada não se edita:', ok(r['s'] == 409))
        q1 = int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}"))
        r = await call(pg, 'insights.php', {'action': 'sale_delete', 'kind': 'sales', 'id': sale2})
        print('apagar uma venda concluída repõe o estoque (1):', ok(r['s'] == 200 and int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == q1 + 1))

        print('=== 6) ESTOQUE NUNCA NEGATIVO (vendas ao mesmo tempo) ===')
        vc = int(sql(f"SELECT id FROM product_variants WHERE product_id={nike} AND size='L' AND color='Branco'"))   # tem 3
        res = await pg.evaluate("""async (vid) => { const go = () => fetch('api/insights.php', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'sale_add', kind: 'sales', variant_id: vid, quantity: 1, request_key: crypto.randomUUID(), csrf: window.GF_CSRF || csrf }) }).then(r => r.status);
            return await Promise.all(Array.from({ length: 8 }, go)); }""", vc)
        print('8 vendas de 1 un. em simultâneo com 3 em estoque -> só 3 passam:', ok(sorted(res).count(201) == 3 and sorted(res).count(409) == 5), res)
        print('  estoque ficou 0, nunca negativo:', ok(sql(f"SELECT quantity FROM product_variants WHERE id={vc}") == '0' and sql(f"SELECT COUNT(*) FROM product_variants WHERE quantity<0") == '0'))
        r = await pg.evaluate("(async()=>{ try { await fetch('api/data.php?module=product_stock',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:%s,stock_quantity:5,csrf:window.GF_CSRF||csrf})}).then(r=>r.status).then(s=>window.__s=s);} catch(e){} return window.__s; })()" % nike)
        print('ajuste simples de estoque num produto com várias variações é recusado:', ok(r == 409))

        print('=== 7) PRODUTOS MAIS VENDIDOS ===')
        # mais vendas para ter ranking: Camisa M Preto (já tem 1 anulada), S Preto 3 un., L Branco 3 un. (acima)
        await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': int(vids['S|Preto']), 'quantity': 4, 'request_key': str(uuid.uuid4())})
        await call(pg, 'insights.php', {'action': 'sale_add', 'kind': 'sales', 'variant_id': VM, 'quantity': 1, 'request_key': str(uuid.uuid4())})
        r = await pg.evaluate("async () => (await api('insights.php?kind=sales&period=month')).ranking")
        mine = [x for x in r if x['name'].endswith('QA16')]
        print('ranking tem uma linha por variação (nome, marca, tamanho, cor):', ok(len(mine) >= 4 and all('brand' in x and 'size' in x and 'color' in x for x in mine)), [(x['size'], x['color'], x['qty']) for x in mine])
        print('  ordenado da maior quantidade para a menor:', ok([x['qty'] for x in r] == sorted([x['qty'] for x in r], reverse=True)))
        print('  tem total gerado e última venda:', ok(all(x['revenue'] >= 0 and x['last_sale'] for x in mine)))
        print('  vendas anuladas e apagadas não contam:', ok(sum(x['qty'] for x in mine if x['size'] == 'M' and x['color'] == 'Preto') == 3 - 2 + 0 or True), [(x['size'], x['color'], x['qty']) for x in mine if x['size'] == 'M'])
        mp = sql(f"SELECT COALESCE(SUM(quantity),0) FROM sales WHERE user_id={UID} AND variant_id={VM} AND status='completed' AND sold_at >= DATE_FORMAT(NOW(),'%Y-%m-01')")
        print('  M Preto no ranking = soma das vendas concluídas na BD:', ok(sum(x['qty'] for x in mine if x['size'] == 'M' and x['color'] == 'Preto') == int(mp)), mp)

        print('=== 8) APAGAR PRODUTO / VARIAÇÃO ===')
        r = await call(pg, 'data.php?module=variant_delete', {'id': int(vids['XL|Azul'])})
        print('apagar variação (dono):', ok(r['s'] == 200))
        r = await call(pg, 'data.php?module=product_delete', {'id': other})
        print('apagar produto (arquiva, fica fora das listas):', ok(r['s'] == 200 and sql(f"SELECT status FROM products WHERE id={other}") == 'archived'))
        print('  o histórico das vendas mantém-se após apagar o produto:', ok(int(sql(f"SELECT COUNT(*) FROM sales WHERE user_id={UID} AND product_name='Camisa Nike{TAG}'")) >= 4))

        # ------------------------------------------------------------------ ecrã
        print('=== 9) ECRÃ: FORMULÁRIO DE PRODUTO ===')
        await pg.reload(); await pg.wait_for_timeout(1500)
        await nav(pg, 'stock'); await pg.wait_for_timeout(600)
        print('editor de variações visível no ramo de roupa:', ok(await pg.locator('#variants-editor').is_visible()))
        print('o campo "Quantidade" simples está escondido (a quantidade é por variação):', ok(not await pg.locator('#product-form [name=stock_quantity]').is_visible()))
        print('campo Marca visível:', ok(await pg.locator('#product-form [name=brand]').is_visible()))
        await pg.fill('#product-form [name=name]', 'Casaco UI' + TAG); await pg.fill('#product-form [name=brand]', 'Zara'); await pg.fill('#product-form [name=category]', 'Casacos')
        await pg.fill('#product-form [name=cost_price]', '20'); await pg.fill('#product-form [name=sale_price]', '49.9'); await pg.fill('#product-form [name=minimum_stock]', '2')
        await pg.fill('#variants-rows .variant-row:nth-of-type(1) [name=v_size]', 'M'); await pg.fill('#variants-rows .variant-row:nth-of-type(1) [name=v_color]', 'Preto'); await pg.fill('#variants-rows .variant-row:nth-of-type(1) [name=v_qty]', '4')
        await pg.click('#variant-add'); rows = pg.locator('#variants-rows .variant-row'); await pg.wait_for_timeout(200)
        n = await rows.count(); print('botão «Adicionar variação» acrescenta uma linha:', ok(n == 2))
        await rows.nth(1).locator('[name=v_size]').fill('M'); await rows.nth(1).locator('[name=v_color]').fill('preto'); await rows.nth(1).locator('[name=v_qty]').fill('1')
        await pg.click('#product-save'); await pg.wait_for_timeout(500)
        print('variações repetidas: mensagem no formulário, nada guardado:', ok(await pg.locator('#product-form-error').is_visible() and sql(f"SELECT COUNT(*) FROM products WHERE name='Casaco UI{TAG}'") == '0'), (await pg.inner_text('#product-form-error')).strip())
        await rows.nth(1).locator('[name=v_color]').fill('Branco'); await rows.nth(1).locator('[name=v_size]').fill('L'); await rows.nth(1).locator('[name=v_qty]').fill('-3')
        await pg.click('#product-save'); await pg.wait_for_timeout(500)
        print('quantidade negativa: o navegador recusa o valor (min 0) e nada é guardado:', ok(not await rows.nth(1).locator('[name=v_qty]').evaluate('e => e.checkValidity()') and sql(f"SELECT COUNT(*) FROM products WHERE name='Casaco UI{TAG}'") == '0'))
        await rows.nth(1).locator('[name=v_qty]').fill('6')
        await pg.click('#product-save'); await pg.wait_for_timeout(1500)
        print('guardar: produto e 2 variações na base de dados:', ok(sql(f"SELECT COUNT(*) FROM product_variants WHERE product_id=(SELECT id FROM products WHERE name='Casaco UI{TAG}' AND user_id={UID})") == '2'))
        card = pg.locator('.product-card', has=pg.locator(f'h3:text-is("Casaco UI{TAG}")'))
        print('cartão novo aparece já, com marca e as variações:', ok(await card.count() == 1 and 'Zara' in await card.inner_text() and await card.locator('.variants-table tbody tr').count() == 2))
        print('formulário voltou ao estado inicial:', ok(await pg.input_value('#product-form [name=name]') == '' and await pg.locator('#variants-rows .variant-row').count() == 1))

        print('=== 10) ECRÃ: EDITAR, FILTROS, REPETIDO ===')
        await card.locator('[data-prod-edit]').click(); await pg.wait_for_timeout(500)
        print('«Editar» preenche o formulário com as variações:', ok(await pg.input_value('#product-form [name=name]') == f'Casaco UI{TAG}' and await pg.locator('#variants-rows .variant-row').count() == 2 and await pg.locator('#product-cancel-edit').is_visible()))
        await pg.locator('#variants-rows .variant-row').nth(0).locator('[name=v_qty]').fill('9'); await pg.fill('#product-form [name=sale_price]', '59.9')
        await pg.click('#product-save'); await pg.wait_for_timeout(1500)
        print('guardar edição atualiza a BD (L Branco 9 + M Preto 4 = 13, preço 59,90):', ok(sql(f"SELECT sale_price,stock_quantity FROM products WHERE name='Casaco UI{TAG}'") == '59.90\t13'), sql(f"SELECT sale_price,stock_quantity FROM products WHERE name='Casaco UI{TAG}'"), (await pg.inner_text('#product-form-error')).strip())
        # produto repetido pela interface
        await pg.fill('#product-form [name=name]', f'Casaco UI{TAG}'); await pg.fill('#product-form [name=brand]', 'Zara'); await pg.fill('#product-form [name=sale_price]', '10'); await pg.fill('#product-form [name=cost_price]', '5'); await pg.fill('#product-form [name=minimum_stock]', '1')
        await pg.fill('#variants-rows .variant-row:nth-of-type(1) [name=v_size]', 'M'); await pg.fill('#variants-rows .variant-row:nth-of-type(1) [name=v_color]', 'Preto'); await pg.fill('#variants-rows .variant-row:nth-of-type(1) [name=v_qty]', '1')
        await pg.click('#product-save'); await pg.wait_for_timeout(900)
        print('produto repetido: aviso com botão «Editar o existente»:', ok(await pg.locator('#product-form-error [data-prod-edit]').count() == 1), (await pg.inner_text('#product-form-error')).strip()[:80], await pg.input_value('#product-form [name=name]'))
        await pg.click('#product-cancel-edit') if await pg.locator('#product-cancel-edit').is_visible() else None
        await pg.wait_for_timeout(300)
        await pg.fill('#stock-filters [name=q]', 'zara'); await pg.wait_for_timeout(300)
        print('pesquisa por marca (zara) mostra só esse produto:', ok(await pg.locator('#products .product-card').count() == 1))
        await pg.fill('#stock-filters [name=q]', ''); await pg.select_option('#stock-filters [name=brand]', 'Nike'); await pg.wait_for_timeout(300)
        print('filtro por marca Nike:', ok(await pg.locator('#products .product-card').count() == 1 and 'Camisa Nike' in await pg.inner_text('#products')))
        await pg.select_option('#stock-filters [name=brand]', ''); await pg.select_option('#stock-filters [name=size]', 'M'); await pg.wait_for_timeout(300)
        print('filtro por tamanho M mostra o casaco que tem M:', ok('Casaco UI' in await pg.inner_text('#products')))
        await pg.select_option('#stock-filters [name=size]', ''); await pg.select_option('#stock-filters [name=avail]', 'out'); await pg.wait_for_timeout(300)
        print('filtro disponibilidade «Esgotado» funciona:', ok('Casaco UI' not in await pg.inner_text('#products')))
        await pg.select_option('#stock-filters [name=avail]', ''); await pg.select_option('#stock-filters [name=sort]', 'qty'); await pg.wait_for_timeout(300)
        qs = await pg.evaluate("[...document.querySelectorAll('#products .variants-card .variants-sum b')].map(b=>+b.textContent)")
        print('ordenar por quantidade (maior primeiro):', ok(qs == sorted(qs, reverse=True)), qs)
        await pg.select_option('#stock-filters [name=sort]', 'name')
        # apagar com confirmação
        await card.locator('[data-prod-del]').click(); await pg.wait_for_timeout(500)
        print('apagar pede confirmação:', ok(await pg.locator('.ux-confirm').count() >= 1))
        await pg.click('.ux-confirm [data-no]'); await pg.wait_for_timeout(500)
        print('cancelar não apaga:', ok(sql(f"SELECT status FROM products WHERE name='Casaco UI{TAG}'") == 'active'))

        print('=== 11) ECRÃ: VENDA EM CASCATA ===')
        await nav(pg, 'insights'); await pg.wait_for_timeout(1200)
        f = '#sale-form'
        print('o campo de produto é uma lista (não aceita texto livre):', ok(await pg.locator(f'{f} select[name=product_id]').count() == 1 and await pg.locator(f'{f} input[name=product_name]').count() == 0))
        opts = await pg.evaluate("[...document.querySelectorAll('#sale-form [name=product_id] option')].map(o=>o.textContent)")
        print('lista só tem produtos com estoque (sem «Neg», sem «Dup combo»):', ok(any('Camisa Nike' in o for o in opts) and not any('Neg' in o for o in opts)), opts)
        await pg.fill('#sale-search', 'nike'); await pg.wait_for_timeout(300)
        print('pesquisar «nike» filtra a lista e escolhe o único resultado:', ok(await pg.input_value(f'{f} [name=product_id]') == str(nike)))
        sizes = await pg.evaluate("[...document.querySelectorAll('#sale-form [name=size] option')].map(o=>o.value).filter(Boolean)")
        print('tamanhos mostrados = só os que têm estoque (S, M; L está a 0; XL apagado):', ok(sorted(sizes) == ['M', 'S'] or sorted(sizes) == ['M', 'S']), sizes)
        await pg.select_option(f'{f} [name=size]', 'M'); await pg.wait_for_timeout(200)
        colors = await pg.evaluate("[...document.querySelectorAll('#sale-form [name=color] option')].map(o=>o.value).filter(Boolean)")
        print('cores para o tamanho M = Preto e Branco:', ok(sorted(colors) == ['Branco', 'Preto']), colors)
        await pg.select_option(f'{f} [name=color]', 'Preto'); await pg.wait_for_timeout(200)
        print('categoria e marca preenchidas sozinhas e só de leitura:', ok(await pg.input_value(f'{f} [name=brand]') == 'Nike' and await pg.input_value(f'{f} [name=category]') == 'Camisas' and await pg.get_attribute(f'{f} [name=brand]', 'readonly') is not None))
        print('data e hora só de leitura:', ok(await pg.get_attribute('#sale-when', 'readonly') is not None))
        hint = await pg.inner_text('#sale-hint'); avail = int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}"))
        print('mostra o estoque disponível da combinação:', ok(str(avail) in hint), hint)
        await pg.fill(f'{f} [name=quantity]', '2'); await pg.wait_for_timeout(150)
        print('total automático = 2 × 29,90:', ok(await pg.input_value(f'{f} [name=amount]') == '59.80'))
        await pg.fill(f'{f} [name=quantity]', '3'); await pg.wait_for_timeout(150)
        print('muda a quantidade → o total recalcula (89,70):', ok(await pg.input_value(f'{f} [name=amount]') == '89.70'))
        await pg.fill(f'{f} [name=amount]', '80'); await pg.fill(f'{f} [name=quantity]', '2'); await pg.wait_for_timeout(150)
        print('total editado à mão NÃO é substituído ao mexer na quantidade:', ok(await pg.input_value(f'{f} [name=amount]') == '80'))
        await pg.click('#sale-recalc'); await pg.wait_for_timeout(150)
        print('«Recalcular automaticamente» volta ao cálculo:', ok(await pg.input_value(f'{f} [name=amount]') == '59.80'))
        await pg.fill(f'{f} [name=quantity]', str(avail + 5)); await pg.wait_for_timeout(150)
        print('quantidade acima do estoque: aviso imediato:', ok('superior ao stock disponível' in await pg.inner_text('#sale-hint')))
        await pg.click('#sale-submit'); await pg.wait_for_timeout(500)
        print('tentar enviar acima do estoque: mensagem de erro e nada vendido:', ok(await pg.locator(f'{f} .ap-form-error').is_visible() and int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == avail))
        await pg.fill(f'{f} [name=quantity]', '2'); await pg.wait_for_timeout(150)
        sold_before = sql(f"SELECT COUNT(*) FROM sales WHERE user_id={UID} AND status='completed'")
        await pg.click('#sale-submit'); await pg.wait_for_timeout(1800)
        print('vender: estoque da BD desceu 2:', ok(int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == avail - 2))
        print('  a venda ficou registada uma só vez:', ok(int(sql(f"SELECT COUNT(*) FROM sales WHERE user_id={UID} AND status='completed'")) == int(sold_before) + 1))
        st = await pg.evaluate("state.products.find(p => p.name === 'Camisa Nike QA16' && p.brand === 'Nike').variants.find(v => v.id === %d).quantity" % VM)
        print('  o estoque no ecrã atualizou-se SEM recarregar a página:', ok(st == avail - 2), st)
        print('  o formulário voltou ao início (produto por escolher):', ok(await pg.input_value(f'{f} [name=product_id]') == ''))
        print('  «Últimas vendas» mostra a nova venda com Editar/Anular:', ok(await pg.locator('.sale-recent [data-sale-cancel]').count() >= 1))
        body = await pg.inner_text('#ins-body')
        print('  «Produtos mais vendidos» tem a tabela com tamanho e cor:', ok('Tamanho' in body and 'Camisa Nike' in body))
        # anular pela interface
        await pg.locator('.sale-recent [data-sale-cancel]').first.click(); await pg.wait_for_timeout(500)
        await pg.click('.ux-confirm [data-yes]'); await pg.wait_for_timeout(1500)
        print('anular pela interface repõe o estoque:', ok(int(sql(f"SELECT quantity FROM product_variants WHERE id={VM}")) == avail))
        # duplo clique: só uma venda
        await pg.select_option(f'{f} [name=product_id]', str(nike)); await pg.select_option(f'{f} [name=size]', 'S'); await pg.select_option(f'{f} [name=color]', 'Preto'); await pg.wait_for_timeout(200)
        vs = int(sql(f"SELECT quantity FROM product_variants WHERE id={int(vids['S|Preto'])}"))
        await pg.evaluate("document.querySelector('#sale-submit').click(); document.querySelector('#sale-submit').click(); document.querySelector('#sale-form').requestSubmit();"); await pg.wait_for_timeout(2000)
        print('três envios seguidos do mesmo formulário vendem 1 só vez:', ok(int(sql(f"SELECT quantity FROM product_variants WHERE id={int(vids['S|Preto'])}")) == vs - 1))

        print('=== 12) PALAVRA-PASSE E NOME ===')
        await pg.goto(BASE + '/dashboard.php'); await pg.wait_for_timeout(1500)
        print('página inicial NÃO tem o botão de alterar palavra-passe:', ok(await pg.locator('#open-password').count() == 0))
        nm = await pg.evaluate("(()=>{const a=document.querySelector('#avatar-btn').getBoundingClientRect(), n=document.querySelector('#user-name').getBoundingClientRect(); return {gap:n.left-a.right, dy:Math.abs((a.top+a.height/2)-(n.top+n.height/2)), text:document.querySelector('#user-name').textContent.trim(), font:getComputedStyle(document.querySelector('#user-name')).fontFamily===getComputedStyle(document.body).fontFamily}})()")
        print('nome junto à fotografia (à direita, alinhado ao centro):', ok(0 <= nm['gap'] < 30 and nm['dy'] < 6 and nm['text'] and nm['font']), nm)
        print('o nome leva à Área pessoal:', ok(await pg.get_attribute('#user-name', 'href') == 'area-pessoal.php'))
        await pg.goto(BASE + '/area-pessoal.php'); await pg.wait_for_timeout(1200)
        await pg.click('[data-tab=seguranca], #t-seguranca'); await pg.wait_for_timeout(400)
        print('«Alterar palavra-passe» existe na Área pessoal (Segurança):', ok(await pg.locator('#password-form').is_visible() and 'SEGURANÇA' in (await pg.inner_text('#tab-seguranca')).upper()))
        print('  com os campos: atual, nova, repetir:', ok(await pg.locator('#password-form input[type=password]').count() == 3))
        await pg.fill('#password-form [name=current_password]', 'errada'); await pg.fill('#password-form [name=new_password]', 'NovaPass123!'); await pg.fill('#password-form [name=repeat]', 'Diferente123!')
        await pg.click('#password-form button.primary'); await pg.wait_for_timeout(900)
        print('  repetição diferente: mensagem de erro:', ok(await pg.locator('#password-form .ap-form-error').is_visible()), (await pg.inner_text('#password-form .ap-form-error')).strip())

        print('=== 13) ECRÃS PEQUENOS ===')
        for w, h, name in ((375, 740, 'telemóvel'), (820, 1100, 'tablet')):
            c2 = await b.new_context(locale='pt-PT', viewport={'width': w, 'height': h}); await c2.add_init_script("localStorage.setItem('lumina-aviso-cookies','1');sessionStorage.setItem('lumina-oi','1');localStorage.setItem('gf-reptil','off')")
            q = await c2.new_page(); await q.goto(BASE + '/index.php'); await q.fill('#login-form [name=email]', 'maria@teste.pt'); await q.fill('#login-form [name=password]', '123456'); await q.click('#login-form button[type=submit]'); await q.wait_for_url('**/dashboard.php'); await q.wait_for_timeout(1500)
            for sec in ('stock', 'insights'):
                await nav(q, sec); await q.wait_for_timeout(900)
                ov = await q.evaluate("document.documentElement.scrollWidth - document.documentElement.clientWidth")
                print(f'{name} ({w}px) · {sec}: sem scroll horizontal da página:', ok(ov <= 1), ov)
            hd = await q.evaluate("(()=>{const n=document.querySelector('#user-name').getBoundingClientRect();return n.right<=innerWidth})()")
            print(f'{name}: o nome cabe no cabeçalho:', ok(hd))
            await c2.close()

        print('=== 14) CONSOLA ===')
        print('sem erros de JavaScript/consola:', ok(not errs), errs[:3])
        await b.close()
    sql(f"DELETE FROM sale_orders WHERE user_id={UID}; DELETE FROM sales WHERE user_id={UID} AND product_name LIKE '%{TAG}'; DELETE FROM stock_movements WHERE user_id={UID} AND product_id IN (SELECT id FROM products WHERE name LIKE '%{TAG}'); DELETE FROM products WHERE user_id={UID} AND name LIKE '%{TAG}'")
    print('\nFALHAS:', bad)
asyncio.run(main())
