import os
import sys, asyncio, json; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from playwright.async_api import async_playwright
from ai_lib import sql
BASE = os.environ.get('LUMINA_URL', 'http://127.0.0.1:8080').rstrip('/'); ok=lambda c: 'PASSOU' if c else '*** FALHOU ***'
async def login(pg,e,p):
    await pg.goto(BASE+'/index.php'); await pg.fill('#login-form [name=email]',e); await pg.fill('#login-form [name=password]',p)
    await pg.click('#login-form button[type=submit]'); await pg.wait_for_url('**/dashboard.php'); await pg.wait_for_timeout(1500)
async def tabs(pg): return await pg.evaluate("[...document.querySelectorAll('#main-menu .nav-tab')].filter(t=>getComputedStyle(t).display!=='none'&&!t.classList.contains('ramo-off')).map(t=>t.dataset.section)")
async def main():
    sql("DELETE FROM login_attempts"); sql("DELETE FROM users WHERE email='quest@lumina.test'")
    from ai_lib import Client
    c=Client(); s,d=c.req('POST','/api/auth.php?action=register',{'name':'Quest Teste','email':'quest@lumina.test','password':'palavra-passe-1'})
    sql("UPDATE users SET email_verified_at=NOW() WHERE email='quest@lumina.test'"); errs=[]
    async with async_playwright() as p:
        b=await p.chromium.launch(); ctx=await b.new_context(locale='pt-PT', viewport={'width':1366,'height':900}); await ctx.add_init_script("localStorage.setItem('gf-reptil','off');localStorage.setItem('lumina-aviso-cookies','1')"); pg=await ctx.new_page()
        pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('console',lambda m:errs.append(m.text) if m.type=='error' and 'open-meteo' not in m.text and 'ERR_FAILED' not in m.text else None)
        await login(pg,'quest@lumina.test','palavra-passe-1')
        print('=== PRIMEIRO ACESSO ===')
        print('o questionário abre sozinho (conta nova):', ok(await pg.is_visible('#profile-modal')), '| passo:', await pg.inner_text('#wiz-eyebrow'), '| título:', await pg.inner_text('#wiz-title'))
        print('   sem ✕ (obrigatório no 1.º acesso):', ok(not await pg.is_visible('#wiz-close')), '| 12 ramos como cartões:', await pg.locator('.profile-choice').count(), ok(await pg.locator('.profile-choice').count()==12))
        await pg.click('#wiz-next'); await pg.wait_for_timeout(200); print('   «Continuar» sem nome: aviso:', repr(await pg.inner_text('#profile-message')), ok('nome' in await pg.inner_text('#profile-message')))
        await pg.fill('[name=business_name]','Barbearia do Zé'); await pg.click('#wiz-next'); await pg.wait_for_timeout(200); print('   sem ramo escolhido: aviso:', repr(await pg.inner_text('#profile-message')), ok('ramo' in await pg.inner_text('#profile-message')))
        await pg.click('[data-profile-type=barber]'); await pg.click('#wiz-next'); await pg.wait_for_timeout(300)
        print('passo 2:', await pg.inner_text('#wiz-eyebrow'), '|', await pg.inner_text('#wiz-title'), '| barra:', await pg.evaluate("document.querySelector('#wiz-progress').getAttribute('aria-valuenow')"), ok('PASSO 2 DE 6' in await pg.inner_text('#wiz-eyebrow')))
        print('   o foco passa para a primeira opção:', ok(await pg.evaluate("document.activeElement.name==='team'")), '| voltar visível:', ok(await pg.is_visible('#wiz-back')))
        await pg.locator('label.wiz-opt:has(input[value=small])').click(); await pg.locator('label.wiz-opt:has(input[value=mobile])').click(); await pg.click('#wiz-next'); await pg.wait_for_timeout(250)
        print('passo 3:', await pg.inner_text('#wiz-title')); 
        for v in ['cash','mbway']: await pg.locator(f'label.wiz-opt:has(input[value={v}])').click()
        await pg.click('#wiz-next'); await pg.wait_for_timeout(250)
        print('passo 4:', await pg.inner_text('#wiz-title'))
        sug=await pg.evaluate("[...document.querySelectorAll('input[name=module]')].filter(i=>i.checked).map(i=>i.value)"); dis=await pg.evaluate("[...document.querySelectorAll('input[name=module]')].filter(i=>i.disabled).map(i=>i.value)")
        print('   sugestões (equipa de 2-5 + em deslocação):', sug, '|', ok('team' in sug and 'time' in sug and 'weather' in sug and 'clients' in sug))
        print('   as 3 essenciais estão ligadas e bloqueadas:', dis, ok(sorted(dis)==['cashflow','overview','reports']))
        await pg.locator('label.wiz-opt:has(input[value=calculator])').click(); await pg.locator('label.wiz-opt:has(input[value=notes])').click()   # desliga Calculadora e Notas
        await pg.click('#wiz-next'); await pg.wait_for_timeout(250); print('passo 5:', await pg.inner_text('#wiz-title'))
        await pg.locator('label.wiz-opt:has(input[value=quarterly])').click(); await pg.locator('label.wiz-opt:has(input[value=independent])').click(); await pg.click('#wiz-next'); await pg.wait_for_timeout(250)
        print('passo 6:', await pg.inner_text('#wiz-title'), '| botão:', await pg.inner_text('#wiz-next'), '| campo do valor escondido até haver objetivo:', ok(not await pg.is_visible('#wiz-amount')))
        await pg.locator('label.wiz-opt:has(input[value=vat])').click(); print('   escolher «IVA» mostra o campo do valor:', ok(await pg.is_visible('#wiz-amount')))
        await pg.fill('[name=goal_amount]','1500'); await pg.locator('label.wiz-opt:has(input[value="3to10k"])').click()
        await pg.click('#wiz-back'); await pg.wait_for_timeout(250); print('   «Voltar» regressa ao passo 5 com a escolha mantida:', ok('Impostos' in await pg.inner_text('#wiz-title') and await pg.is_checked('input[name=vat][value=quarterly]')))
        await pg.click('#wiz-next'); await pg.wait_for_timeout(250); print('   e ao avançar o valor do objetivo continua lá:', ok(await pg.input_value('[name=goal_amount]')=='1500'))
        await pg.click('#wiz-next'); await pg.wait_for_selector('.wiz-done',timeout=8000); await pg.wait_for_timeout(500)
        print('\n=== CONCLUÍDO ===')
        print('ecrã final:', await pg.inner_text('#wiz-title'), '|', (await pg.inner_text('.wiz-chips')).replace('\n',' · ')[:100]); print('   avisa da conta de reserva criada:', ok('conta de reserva' in await pg.inner_text('.wiz-done')))
        row=sql("SELECT business_type, enabled_modules, onboarding FROM business_profiles bp JOIN users u ON u.id=bp.user_id WHERE u.email='quest@lumina.test'").split('\t'); ob=json.loads(row[2]); mods=json.loads(row[1])
        print('guardado na BD: ramo', row[0], '| respostas:', ob, ok(ob['team']=='small' and ob['place']=='mobile' and ob['pay']==['cash','mbway'] and ob['vat']=='quarterly' and ob['ss']=='independent' and ob['goal']=='vat' and ob['goal_amount']==1500 and ob['revenue']=='3to10k'))
        print('   módulos guardados:', mods, ok('calculator' not in mods and 'notes' not in mods and 'team' in mods and {'overview','cashflow','reports'}<=set(mods)))
        acc=sql("SELECT a.name, a.type, a.target_amount FROM accounts a JOIN users u ON u.id=a.user_id WHERE u.email='quest@lumina.test'"); print('   contas na BD:', repr(acc), ok('Reserva para o IVA' in acc and 'reserve' in acc and '1500' in acc))
        await pg.click('#wiz-next'); await pg.wait_for_timeout(500); print('«Entrar no painel» fecha a janela:', ok(not await pg.is_visible('#profile-modal')))
        t=await tabs(pg); print('abas no menu agora:', t, ok('calculator' not in t and 'notes' not in t and 'team' in t and 'time' in t and 'weather' in t))
        print('banner do painel acompanha o ramo:', await pg.inner_text('#business-title'), '|', await pg.inner_text('#profile-badge'), ok('Barbearia do Zé' in await pg.inner_text('#business-title')))
        await pg.reload(); await pg.wait_for_timeout(1800); t2=await tabs(pg); print('depois de recarregar a escolha mantém-se:', ok(t2==t and not await pg.is_visible('#profile-modal')))
        print('\n=== REFAZER ===')
        await pg.click('#change-profile'); await pg.wait_for_timeout(500); print('«Alterar ramo» abre com os dados guardados:', await pg.input_value('[name=business_name]'), '| ramo marcado:', await pg.evaluate("document.querySelector('.profile-choice.selected')?.dataset.profileType"), ok(await pg.evaluate("document.querySelector('.profile-choice.selected')?.dataset.profileType")=='barber'), '| agora tem ✕:', ok(await pg.is_visible('#wiz-close')))
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(300); print('   Esc fecha sem gravar:', ok(not await pg.is_visible('#profile-modal')))
        await pg.goto(BASE+'/area-pessoal.php#empresa'); await pg.wait_for_timeout(1200); await pg.click('#redo-onboarding'); await pg.wait_for_url('**/dashboard.php**'); await pg.wait_for_timeout(1800)
        print('«Refazer o questionário» na Área pessoal abre o assistente:', ok(await pg.is_visible('#profile-modal')), '| endereço limpo:', ok('questionario' not in pg.url))
        await pg.click('#wiz-next'); await pg.wait_for_timeout(300); await pg.click('#wiz-next'); await pg.wait_for_timeout(300); await pg.click('#wiz-next'); await pg.wait_for_timeout(300)
        print('   passo 4 traz as abas que escolhi antes (Notas desligada):', ok(not await pg.is_checked('input[name=module][value=notes]') and await pg.is_checked('input[name=module][value=team]')))
        await pg.keyboard.press('Escape'); await ctx.close()
        print('\n=== ATALHO ===')
        ctx=await b.new_context(locale='pt-PT', viewport={'width':1366,'height':900}); await ctx.add_init_script("localStorage.setItem('lumina-aviso-cookies','1')"); pg=await ctx.new_page(); sql("DELETE FROM business_profiles WHERE user_id=(SELECT id FROM users WHERE email='quest@lumina.test')"); sql("DELETE FROM accounts WHERE user_id=(SELECT id FROM users WHERE email='quest@lumina.test')")
        await login(pg,'quest@lumina.test','palavra-passe-1'); await pg.fill('[name=business_name]','Loja Rápida'); await pg.click('[data-profile-type=clothing]'); await pg.click('#wiz-quick'); await pg.wait_for_selector('.wiz-done',timeout=8000)
        print('«Usar sugestões e entrar» grava logo:', ok('Está tudo pronto' in await pg.inner_text('#wiz-title')), '| respostas guardadas:', repr(sql("SELECT IFNULL(onboarding,'NULL') FROM business_profiles bp JOIN users u ON u.id=bp.user_id WHERE u.email='quest@lumina.test'")))
        await pg.click('#wiz-next'); await pg.wait_for_timeout(500); t=await tabs(pg); print('   abas sugeridas para uma loja de roupa, a trabalhar sozinho:', t, ok('stock' in t and 'clients' in t and 'insights' in t and 'team' not in t))
        await ctx.close(); await b.close()
    print('\nERROS JS:', errs or 'nenhum')
    sql("DELETE FROM users WHERE email='quest@lumina.test'")
asyncio.run(main())
